MyFirstASPNETWebApp/Models/GradeCalcModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MyFirstASPNETWebApp.Models
{

    //This is the model that also does the range validation to make sure that all values are between 0 and 100.

    public class GradeCalcModel
    {
        [Required]
        [Range(typeof(int), "0", "100", ErrorMessage = "Please enter an Exam average between 0 and 100")]
        public int Exams { get; set; }
        [Required]
        [Range(typeof(int), "0", "100", ErrorMessage = "Please enter an Intex average between 0 and 100")]
        public int Intex { get; set; }
        [Required]
        [Range(typeof(int), "0", "100", ErrorMessage = "Please enter a Group Project average between 0 and 100")]
        public int GroupProjects { get; set; }
        [Required]
        [Range(typeof(int), "0", "100", ErrorMessage = "Please enter an Assigments average between 0 and 100")]
        public int Assignments { get; set; }
        [Required]
        [Range(typeof(int), "0" , "100", ErrorMessage = "Please enter a Quizzes average between 0 and 100")]
        public int Quizzes { get; set; }
    }
}

MyFirstASPNETWebApp/Controllers/pagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyFirstASPNETWebApp.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MyFirstASPNETWebApp.Controllers
{
    public class pagesController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            //throw new IndexOutOfRangeException();
            return View();
         
        }
        [HttpGet]
        public IActionResult GPACalculator()
        {
            return View();

        }
        [HttpPost]
        public IActionResult GPACalculator(GradeCalcModel model)
        {
            return View();

        }
    }
}

MyFirstASPNETWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@*This is the shared page for page elements that we want to share across all views.*@
<html>
<head>
    <!--Head, with bootstrap link, favicon for the tab icon, and css link.-->
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>

    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/default.css" rel="stylesheet" />
    <link rel="icon" href="~/img/icon.png">
</head>
<header>
    <br />
    <nav>
        <a asp-controller="pages" asp-action="Index">Home</a>
        <a asp-controller="pages" asp-action="GPACalculator">GPA Calculator</a>
    </nav>
    <br />
</header>
<body>


    <div>
        @RenderBody()
    </div>



</body>
</html>

<!--Footer with my name and copyright.-->
<footer>
    <br />
    Copyright 2022, Benjamin Kloepfer

</footer>
<script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
<script src="~/lib/jquery/jquery-3.6.0.min.js"></script>
<script src="~/js/gradeCalc.js"></script>

MyFirstASPNETWebApp/Views/pages/GPACalculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "GPA Calculator";
}

@model MyFirstASPNETWebApp.Models.GradeCalcModel

<!--The grade calculator form.-->
<br />
<h2>Grade Calculator</h2>
<br />
<form method="post">
    <label>Assignment Percentage</label>
    <input id="AS" asp-for="Assignments"/><br />
    <label>Group Project Percentage</label>
    <input id="GP" asp-for="GroupProjects" /><br />
    <label>Quizzes Percentage</label>
    <input id="QZ" asp-for="Quizzes"/><br />
    <label>Exams Percentage</label>
    <input id="EX" asp-for="Exams"/><br />
    <label>INTEX Percentage</label>
    <input id="IN" asp-for="Intex"/><br />
    <input id="BtnSend" type="submit" value="Calculate Grade" />
    <br />
    <div asp-validation-summary="All"></div>
</form>
<br />

<!--Scripts for bootstrap and for the calculator.-->

<script src="~/js/gradeCalc.js"></script>

MyFirstASPNETWebApp/Views/pages/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Ben's Home Page";
}

<!DOCTYPE html>


<!--Header with my name.-->
<header>
    
<h1>Ben Kloepfer</h1>
<br />
</header>



<!--Body, which includes a picture of me with my cars, a paragraph about my goals for the class and beyond, and finally,
a list of the top three jobs I want to do after graduating.-->

<br />
<img id="picme" src="~/img/cars.png" width=250 />
<p>Ben is an IS student and loves cars.</p>
<br />
<p>
    I can't wait to get more comfortable with programming and to be able to make beautiful and functional websites.
    <br />
    This semester I look forward to gaining skills to use in designing websites for the rest of my career.
</p>
<h2>My top 3 careers:</h2>
<ul>
    <li>1. Web designer</li>
    <br />
    <li>2. Database technician</li>
    <br />
    <li>3. Data Analyst</li>

</ul>